import { mkdir, writeFile } from "node:fs/promises";
import {
	applyTurn,
	createInitialState,
	createState,
	getLegalTurns,
	getOutcome,
	positionKey,
} from "../src/core/engine";
import type { GameState } from "../src/core/engine";
import type { KnowledgeEntry, KnowledgeFile } from "../src/ai/knowledge";
import { SearchEngine } from "../src/ai/search";
import { generateTwoPiece } from "./tablebase-generator";

const engine = new SearchEngine();
const opening: KnowledgeEntry[] = [];
const queue: GameState[] = [createInitialState()];
const seen = new Set<string>();
while (queue.length && opening.length < 128) {
	const state = queue.shift()!;
	const key = positionKey(state);
	if (seen.has(key) || getOutcome(state)) continue;
	seen.add(key);
	const result = engine.fixedDepth(state, 4);
	if (result.move)
		opening.push({
			key,
			from: result.move.from,
			path: result.move.path,
			score: result.score,
			depth: 4,
		});
	// A reproducible, originally generated breadth-first tree of opening replies.
	if (state.ply < 5)
		for (const move of getLegalTurns(state)) queue.push(applyTurn(state, move));
}

const endgame: KnowledgeEntry[] = [];
let seed = 0x41535452;
const random = () => {
	seed ^= seed << 13;
	seed ^= seed >>> 17;
	seed ^= seed << 5;
	return seed >>> 0;
};
seen.clear();
while (endgame.length < 1024) {
	const board = Array<number>(32).fill(0);
	const pieces =
		endgame.length % 3 === 0
			? [2, 4]
			: endgame.length % 2
				? [1, 2, 4]
				: [2, 3, 4];
	for (const piece of pieces) {
		let square = random() % 32;
		while (
			board[square] ||
			(piece === 1 && square >= 28) ||
			(piece === 3 && square < 4)
		)
			square = random() % 32;
		board[square] = piece;
	}
	const state = createState(board, random() % 2 ? "dark" : "light");
	const key = positionKey(state);
	if (seen.has(key) || getOutcome(state)) continue;
	seen.add(key);
	const result = engine.fixedDepth(state, 6);
	if (result.move)
		endgame.push({
			key,
			from: result.move.from,
			path: result.move.path,
			score: result.score,
			depth: 6,
		});
}

await mkdir("public/data", { recursive: true });
const tablebase = generateTwoPiece();
const tablebaseText = JSON.stringify(tablebase);
if (Buffer.byteLength(tablebaseText) > 2 * 1024 * 1024)
	throw new Error("Two-piece tablebase exceeds dataset cap");
await writeFile("public/data/two-piece.json", tablebaseText + "\n");
console.log(
	`two-piece: ${tablebase.entries.length} positions, ${Buffer.byteLength(tablebaseText)} bytes`,
);
for (const [kind, entries] of [
	["opening", opening],
	["endgame", endgame],
] as const) {
	const data: KnowledgeFile = {
		version: 1,
		kind,
		description:
			kind === "opening"
				? "Original Astra opening guidance, generated by depth-4 search. Move ordering only; no externally sourced book."
				: "Original sparse 2/3-piece endgame guidance, generated by depth-6 search. This is not an exhaustive or solved tablebase. Move ordering only; live draw context always controls adjudication.",
		entries,
	};
	const text = JSON.stringify(data);
	if (Buffer.byteLength(text) > 2 * 1024 * 1024)
		throw new Error(`${kind} exceeds dataset cap`);
	await writeFile(`public/data/${kind}.json`, text + "\n");
	console.log(
		`${kind}: ${entries.length} positions, ${Buffer.byteLength(text)} bytes`,
	);
}
